INFO:     Will watch for changes in these directories: ['/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/backend']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [12381] using StatReload
INFO:     Started server process [12407]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/models.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12407]
INFO:     Started server process [29520]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/api.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [29520]
INFO:     Started server process [29563]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 181, in serialize_response
    return field.serialize(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 151, in serialize
    return self._type_adapter.dump_python(
  File "/Users/pwablo/Documents/GitHub/emg-c3d-analyzer/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 572, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>
WARNING:  StatReload detected changes in 'backend/export_utils.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [29563]
INFO:     Started server process [31888]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/api.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [31888]
INFO:     Started server process [32411]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/api.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [32411]
INFO:     Started server process [32483]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/emg_analysis.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [32483]
INFO:     Started server process [33031]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/emg_analysis.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [33031]
INFO:     Started server process [34340]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'backend/api.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [34340]
INFO:     Started server process [34784]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
